export interface Wallet {
  id: string;
  address: string;
  label: string;
  category: 'whale' | 'dev' | 'influencer' | 'institution' | 'trader' | 'kol';
  totalPnl: number;
  winRate: number;
  totalTrades: number;
  favoriteTokens: string[];
  avatar?: string;
  verified?: boolean;
  description?: string;
  socials?: {
    twitter?: string;
    telegram?: string;
  };
}

export interface Trade {
  id: string;
  walletId: string;
  tokenSymbol: string;
  tokenName: string;
  tradeType: 'buy' | 'sell';
  amount: number;
  price: number;
  pnl: number;
  timestamp: string;
}

export const categories = [
  { id: 'whale', name: 'Whales', description: 'High volume traders with $1M+ portfolios', color: 'bg-purple-500', icon: '🐋' },
  { id: 'dev', name: 'Developers', description: 'Project founders and protocol developers', color: 'bg-blue-500', icon: '💻' },
  { id: 'influencer', name: 'Influencers', description: 'CT personalities and alpha callers', color: 'bg-pink-500', icon: '📢' },
  { id: 'institution', name: 'Institutions', description: 'VCs, funds, and market makers', color: 'bg-amber-500', icon: '🏦' },
  { id: 'trader', name: 'Pro Traders', description: 'Consistently profitable day traders', color: 'bg-green-500', icon: '📈' },
  { id: 'kol', name: 'KOLs', description: 'Key opinion leaders and top traders', color: 'bg-orange-500', icon: '👑' },
];

export const wallets: Wallet[] = [
  {
    id: '1',
    address: 'AVAZvHLR2PcWpDf8BXY4rVxNHYRBytycHkcB5z5QNXYm',
    label: 'Alpha Insider',
    category: 'whale',
    totalPnl: 13374955,
    winRate: 82.4,
    totalTrades: 1745,
    favoriteTokens: ['Fartcoin', 'ai16z', 'TRUMP', '$WIF', 'MOODENG'],
    verified: true,
    description: 'Top-performing smart money wallet with $13.3M realized P&L. Active across memecoins and blue chips.',
    socials: { twitter: '@alphainsider' }
  },
  {
    id: '2',
    address: '4UwK5AE6Djdf3MfwtPGE8pFYD47MhU9fiStDVmSHJVMB',
    label: 'DEX Pro Trader',
    category: 'trader',
    totalPnl: 234807,
    winRate: 76.3,
    totalTrades: 1905,
    favoriteTokens: ['HBULL', 'wumc', 'FARM', 'BOXABL', 'PARQ'],
    verified: true,
    description: 'Consistent DEX trader with $234k+ profit across 1,900+ trades.',
  },
  {
    id: '3',
    address: '5fM9cY5GMo8QtTmxuvNx7bWFUoNhdQ1H5w8bMdXGVtaH',
    label: 'MemeCoin Specialist',
    category: 'trader',
    totalPnl: 83847,
    winRate: 71.5,
    totalTrades: 1462,
    favoriteTokens: ['GTAVI', 'ANSEM', 'TrumpCoin', 'Embrace', 'Robbinghood'],
    verified: false,
    description: 'Memecoin trader specializing in early entries. $83k+ realized P&L.',
  },
  {
    id: '4',
    address: 'GV6UUmNxz2RpKxmNAPadYKb7uQpszwqQAu3qLJxVdC52',
    label: 'Ansem',
    category: 'influencer',
    totalPnl: 0,
    winRate: 0,
    totalTrades: 24,
    favoriteTokens: ['PUMP', 'ZAUTH', 'CLAW', 'ATELIER', 'NEST'],
    verified: true,
    description: 'Legendary crypto KOL. Known for early calls and massive market impact on Solana.',
    socials: { twitter: '@ansem' }
  },
  {
    id: '5',
    address: 'HUpPyLU8KWisCAr3mzWy2FKT6uuxQ2qGgJQxyTpDoes5',
    label: 'Mega Whale',
    category: 'whale',
    totalPnl: 17501756,
    winRate: 68.5,
    totalTrades: 3452,
    favoriteTokens: ['TRUMP', 'BUZZ', 'ACT'],
    verified: true,
    description: 'Massive whale wallet with $17.5M+ in realized profits. Heavy trader on political and narrative tokens.',
  },
  {
    id: '6',
    address: 'ECCKBDWX3MkEcf3bULbLBb9FvrEQLsmPMFTKFpvjzqgP',
    label: 'Market Master',
    category: 'whale',
    totalPnl: 12523407,
    winRate: 74.2,
    totalTrades: 2890,
    favoriteTokens: ['TRUMP', 'MELANIA', 'SNAI'],
    verified: true,
    description: 'Whale with $12.5M+ P&L. Strategic trader across multiple token narratives.',
  },
  {
    id: '7',
    address: '3tc4BVAdzjr1JpeZu6NAjLHyp4kK3iic7TexMBYGJ4Xk',
    label: 'Alpha Whale',
    category: 'whale',
    totalPnl: 9837772,
    winRate: 71.8,
    totalTrades: 2156,
    favoriteTokens: ['MELANIA', 'TRUMP', 'jellyjelly'],
    verified: true,
    description: 'Nearly $10M in realized profits. Smart money whale with excellent timing.',
  },
  {
    id: '8',
    address: 'DKgvpfttzmJqZXdavDwTxwSVkajibjzJnN2FA99dyciK',
    label: 'Crypto Whale',
    category: 'whale',
    totalPnl: 8148460,
    winRate: 65.9,
    totalTrades: 1890,
    favoriteTokens: ['MELANIA', 'TRUMP', 'CHILLGUY'],
    verified: true,
    description: '$8M+ whale with diverse portfolio of high-cap memecoins.',
  },
  {
    id: '9',
    address: '636N7frU8bUwYfyUAtvMQQsXhTFRuSWjxnEZihr5axGV',
    label: 'Institution Whale',
    category: 'institution',
    totalPnl: 5208766,
    winRate: 62.3,
    totalTrades: 987,
    favoriteTokens: ['TRUMP', 'KWAII', 'jellyjelly'],
    verified: true,
    description: 'Institutional-grade wallet with $5.2M+ profits. Large position sizes.',
  },
  {
    id: '10',
    address: '7SDs3PjT2mswKQ7Zo4FTucn9gJdtuW4jaacPA65BseHS',
    label: 'KOL Trader',
    category: 'influencer',
    totalPnl: 4187317,
    winRate: 69.4,
    totalTrades: 1567,
    favoriteTokens: ['MELANIA', 'LIBRA', 'TWC'],
    verified: true,
    description: 'KOL-level wallet with $4.1M+ P&L. Active in memecoin trading.',
    socials: { twitter: '@koltradesol' }
  },
  {
    id: '11',
    address: '9jyqFiLnruggwNn4EQwBNFXwpbLM9hrA4hV59ytyAVVz',
    label: 'Core Trader',
    category: 'trader',
    totalPnl: 2927456,
    winRate: 73.6,
    totalTrades: 2345,
    favoriteTokens: ['Pnut', 'TRUMP', 'NOLAND'],
    verified: true,
    description: 'Consistent $2.9M+ profit trader. High win rate on memecoin plays.',
  },
  {
    id: '12',
    address: '2tgaERy66PYPEovadPh5y7coWjyURTmvKgdrHd9DAoxw',
    label: 'Smart Whale',
    category: 'whale',
    totalPnl: 2805325,
    winRate: 67.8,
    totalTrades: 1123,
    favoriteTokens: ['jellyjelly', 'ZAILGO', 'ALON'],
    verified: true,
    description: 'Smart money whale with $2.8M+ in realized profits.',
  },
  {
    id: '13',
    address: '2RssnB7hcrnBEx55hXMKT1E7gN27g9ecQFbbCc5Zjajq',
    label: 'Mega Trader',
    category: 'trader',
    totalPnl: 2350957,
    winRate: 70.2,
    totalTrades: 1789,
    favoriteTokens: ['MELANIA', 'TWC', 'CAINAM'],
    verified: true,
    description: 'Top performer with $2.3M+ P&L. Diversified trading approach.',
  },
  {
    id: '14',
    address: 'H72yLkhTnoBfhBTXXaj1RBXuirm8s8G5fcVh2XpQLggM',
    label: 'GMGN Alpha',
    category: 'trader',
    totalPnl: 2083950,
    winRate: 66.4,
    totalTrades: 2340,
    favoriteTokens: ['GOAT', 'MOODENG', 'LUCE'],
    verified: false,
    description: 'Tracked by GMGN as smart money. $2M+ across trending tokens.',
  },
  {
    id: '15',
    address: '4Be9CvxqHW6BYiRAxW9Q3xu1ycTMWaL5z8NX4HR3ha7t',
    label: 'Profit Hunter',
    category: 'trader',
    totalPnl: 1779906,
    winRate: 72.1,
    totalTrades: 1256,
    favoriteTokens: ['MITCH', 'DOLAN', 'XD'],
    verified: false,
    description: 'Skilled trader with $1.7M+ in realized gains.',
  },
  {
    id: '16',
    address: 'dVs7zZksjFuq73xbtUC62brFXYYuxCuPSG4wZeGiHck',
    label: 'Political Trader',
    category: 'trader',
    totalPnl: 1753159,
    winRate: 64.8,
    totalTrades: 890,
    favoriteTokens: ['TRUMP', 'DADDY', 'MUSKIT'],
    verified: false,
    description: 'Focuses on political and narrative-driven tokens. $1.75M+ P&L.',
  },
  {
    id: '17',
    address: 'pndujwi7BeaRRenYHSShyNQXAdBNEzKDR5jgzbheJFT',
    label: 'DeFi Whale',
    category: 'whale',
    totalPnl: 1363417,
    winRate: 69.5,
    totalTrades: 1567,
    favoriteTokens: ['super-b2b', 'MELANIA', 'Valentine'],
    verified: false,
    description: '$1.36M+ whale wallet. Active in both memecoin and DeFi tokens.',
  },
  {
    id: '18',
    address: '9vWutdTBs66hWkeCmxaLFpkKy4q5RSe8DsFjfdxj5yFA',
    label: 'Seasoned Trader',
    category: 'trader',
    totalPnl: 1062539,
    winRate: 70.8,
    totalTrades: 987,
    favoriteTokens: ['FWOG', 'NEIRO', 'MLG'],
    verified: false,
    description: '$1M+ trader with proven track record across multiple tokens.',
  },
  {
    id: '19',
    address: '2HWT2KLLdN2wxYTqdSuko5SBzg2SEJASgV4GE2tD7TML',
    label: 'Blue Chip Whale',
    category: 'whale',
    totalPnl: 1026619,
    winRate: 61.3,
    totalTrades: 567,
    favoriteTokens: ['MELANIA', 'BOXABL', 'TERRA'],
    verified: false,
    description: 'Whale with $1M+ P&L focused on blue chip memecoins.',
  },
  {
    id: '20',
    address: '4Bq5yvgoiZDsukGERb7aM52jDmbVPCpoihbztscZ5PeM',
    label: 'Emerging Whale',
    category: 'whale',
    totalPnl: 1010751,
    winRate: 75.2,
    totalTrades: 567,
    favoriteTokens: ['Quant', 'CHILLGUY', 'HFC'],
    verified: false,
    description: 'Rising whale with $1M+ profits. High win rate of 75%.',
  },
  {
    id: '21',
    address: 'EdDCRfDDeiiDXdntrP59abH4DXHFNU48zpMPYisDMjA7',
    label: 'Meme Hunter',
    category: 'trader',
    totalPnl: 1150765,
    winRate: 68.4,
    totalTrades: 1345,
    favoriteTokens: ['moonpig', 'FLOOF', 'FWOG'],
    verified: false,
    description: 'Dedicated memecoin hunter with $1.15M+ P&L.',
  },
  {
    id: '22',
    address: '7Dt5oUpxHWuKH8bCTXDLz2j3JyxA7jEmtzqCG6pnh96X',
    label: 'Narrative Trader',
    category: 'trader',
    totalPnl: 346518,
    winRate: 72.5,
    totalTrades: 890,
    favoriteTokens: ['MELANIA', 'TRUMP', 'MLG'],
    verified: false,
    description: 'Skilled narrative trader with $346k+ profits.',
  },
  {
    id: '23',
    address: 'BD7oWkEQsUwE8sj4UT7jtrGjHC8Gq1iRqXY7U6DTbJpf',
    label: 'Niche Trader',
    category: 'trader',
    totalPnl: 303695,
    winRate: 65.2,
    totalTrades: 789,
    favoriteTokens: ['TRUMP', 'MELLA', 'MMGA'],
    verified: false,
    description: 'Niche trader with $303k+ P&L in political tokens.',
  },
  {
    id: '24',
    address: 'HrTZPWV4ZPebBiwyzoTBajCD49kQqVwf4dwsLuYG8CXX',
    label: 'Degen Trader',
    category: 'trader',
    totalPnl: 732931,
    winRate: 63.7,
    totalTrades: 1567,
    favoriteTokens: ['IRONYMAN', 'BINARY'],
    verified: false,
    description: 'Degen trader with $732k+ in realized profits.',
  },
  {
    id: '25',
    address: '9xaQ3jPuaRC5KaNkov7Lw6Bq1gKjRp4wD67v6pK1MdK1',
    label: '9xaQ3j...1MdK1',
    category: 'influencer',
    totalPnl: 2689737,
    winRate: 0,
    totalTrades: 1361,
    favoriteTokens: ["$WIF", "Bonk", "DITH"],
    verified: false,
    description: 'Robinhood KOL. $2,689,737 P&L across 50 tokens.',
  },
  {
    id: '26',
    address: '9XVWfqzavraezfvS38v8xcZepHYxcNKtnNMEKpPXEwTN',
    label: '9XVWfq...XEwTN',
    category: 'influencer',
    totalPnl: 1993962,
    winRate: 0,
    totalTrades: 1348,
    favoriteTokens: ["Ani", "TripleT", "GOR"],
    verified: false,
    description: 'Robinhood KOL. $1,993,962 P&L across 50 tokens.',
  },
  {
    id: '27',
    address: '3BH2uRNcbVhCJNxoHqiwP8gXV69LmAtPxdaaRR9DzJ1a',
    label: '3BH2uR...DzJ1a',
    category: 'influencer',
    totalPnl: 1391740,
    winRate: 0,
    totalTrades: 2888,
    favoriteTokens: ["Fartcoin", "IO", "TRUMP"],
    verified: false,
    description: 'Robinhood KOL. $1,391,740 P&L across 50 tokens.',
  },
  {
    id: '28',
    address: 'EPKrfFVt2CoaUnCo8eMauH3PEsK3rwyPQefxGd1zEi8m',
    label: 'EPKrfF...zEi8m',
    category: 'influencer',
    totalPnl: 946560,
    winRate: 0,
    totalTrades: 432,
    favoriteTokens: ["MELANIA", "TRUMP", "YZY"],
    verified: false,
    description: 'Robinhood KOL. $946,560 P&L across 50 tokens.',
  },
  {
    id: '29',
    address: 'EFqaGUqEtoSqz4FZF7Kgf9p8VYAH8WN9vqrkF9E4nx2K',
    label: 'EFqaGU...4nx2K',
    category: 'influencer',
    totalPnl: 790608,
    winRate: 0,
    totalTrades: 383,
    favoriteTokens: ["META", "KOHAI", "DEBT"],
    verified: false,
    description: 'Robinhood KOL. $790,608 P&L across 50 tokens.',
  },
  {
    id: '30',
    address: '7yXdiQ7ufCLKb1UUEPXuaqpwnodbVqmmVbH59qwFSB1x',
    label: '7yXdiQ...FSB1x',
    category: 'influencer',
    totalPnl: 666616,
    winRate: 0,
    totalTrades: 8136,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $666,616 P&L across 1 tokens.',
  },
  {
    id: '31',
    address: '3U6AdFFfrDJ6PbwJCi21vYtayKgB8gUUTBBpcpsaJ9G1',
    label: '3U6AdF...aJ9G1',
    category: 'influencer',
    totalPnl: 657081,
    winRate: 0,
    totalTrades: 7939,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $657,081 P&L across 1 tokens.',
  },
  {
    id: '32',
    address: '8sh7DVftVU2dEbyUt7KoZs9KngXx95Gvz2DRk3tuKAJY',
    label: '8sh7DV...uKAJY',
    category: 'influencer',
    totalPnl: 612970,
    winRate: 0,
    totalTrades: 8184,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $612,970 P&L across 1 tokens.',
  },
  {
    id: '33',
    address: '4vixhVdCKpekJFyzYN6ABDmrh4aJKGSZpSqURXfB6ZyC',
    label: '4vixhV...B6ZyC',
    category: 'influencer',
    totalPnl: 612576,
    winRate: 0,
    totalTrades: 8050,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $612,576 P&L across 1 tokens.',
  },
  {
    id: '34',
    address: '6Nwh13DMMP6xLuMPeLbt14o2KdbiiXYETcCLWjYWaV7L',
    label: '6Nwh13...WaV7L',
    category: 'influencer',
    totalPnl: 533889,
    winRate: 0,
    totalTrades: 556,
    favoriteTokens: ["pippin", "Punch", "WAR"],
    verified: false,
    description: 'Robinhood KOL. $533,889 P&L across 50 tokens.',
  },
  {
    id: '35',
    address: 'Dk4na3gi8HYrrnFDcRgVfET23Ltm7AxbzvPpGyHaXwQJ',
    label: '0xuberM',
    category: 'influencer',
    totalPnl: 515108,
    winRate: 0,
    totalTrades: 899,
    favoriteTokens: ["unc", "Buttcoin", "Goblin"],
    verified: false,
    description: 'Robinhood KOL. $515,108 P&L across 50 tokens.',
  },
  {
    id: '36',
    address: 'Bn3BSYQKLa1aMoeLLUF4ZEsqBAbP3evsxiGBSWvaCY1k',
    label: 'Bn3BSY...aCY1k',
    category: 'influencer',
    totalPnl: 503007,
    winRate: 0,
    totalTrades: 6969,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $503,007 P&L across 1 tokens.',
  },
  {
    id: '37',
    address: '4Y84ZayuVutuW2e1Lq8qfq5JYwYkTn8CtutmZs3jW8oM',
    label: '4Y84Za...jW8oM',
    category: 'influencer',
    totalPnl: 491653,
    winRate: 0,
    totalTrades: 107,
    favoriteTokens: ["USDG", "kySOL", "USX"],
    verified: false,
    description: 'Robinhood KOL. $491,653 P&L across 5 tokens.',
  },
  {
    id: '38',
    address: '6jco9JKp5udbGJ8qPB1eCqjuXj7vcTzGpW9926ouDzAs',
    label: '6jco9J...uDzAs',
    category: 'influencer',
    totalPnl: 489479,
    winRate: 0,
    totalTrades: 7669,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $489,479 P&L across 1 tokens.',
  },
  {
    id: '39',
    address: '3v29xG5e1yjgWkokPAaKBhwxbF5DzJokMQVvQbecuYAV',
    label: 'Cex buys',
    category: 'influencer',
    totalPnl: 444245,
    winRate: 0,
    totalTrades: 603,
    favoriteTokens: ["DAFLE"],
    verified: false,
    description: 'Robinhood KOL. $444,245 P&L across 1 tokens.',
  },
  {
    id: '40',
    address: 'E1oQG6gZsdSqoLcvW8pKWsxh5W4bd6GQYL6xyhRw3Lg8',
    label: 'E1oQG6...w3Lg8',
    category: 'influencer',
    totalPnl: 430893,
    winRate: 0,
    totalTrades: 9664,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $430,893 P&L across 1 tokens.',
  },
  {
    id: '41',
    address: '9dbcLC76Cr32kkSt2ayEzkYxxptwtkyAnSYNUsnnzK8A',
    label: 'XXX',
    category: 'influencer',
    totalPnl: 287016,
    winRate: 0,
    totalTrades: 768,
    favoriteTokens: ["Buttcoin", "Shellraiser", "FWOG"],
    verified: false,
    description: 'Robinhood KOL. $287,016 P&L across 50 tokens.',
  },
  {
    id: '42',
    address: '6mWEJG9LoRdto8TwTdZxmnJpkXpTsEerizcGiCNZvzXd',
    label: 'slingoorio.sol',
    category: 'influencer',
    totalPnl: 254347,
    winRate: 0,
    totalTrades: 8138,
    favoriteTokens: ["LMAO!", "WOJAK", "SPSC"],
    verified: false,
    description: 'Robinhood KOL. $254,347 P&L across 50 tokens.',
  },
  {
    id: '43',
    address: 'DaUBRKnAjuqzozUjkH4QuVJUJiSmrbnLbCeqAgwA6dGF',
    label: 'DaUBRK...A6dGF',
    category: 'influencer',
    totalPnl: 254294,
    winRate: 0,
    totalTrades: 908,
    favoriteTokens: ["PENGUIN", "Chonketha", "WhiteHouse"],
    verified: false,
    description: 'Robinhood KOL. $254,294 P&L across 50 tokens.',
  },
  {
    id: '44',
    address: 'HvjUNaVTHZqZ2AqnJJPGJ3GJkJhhbvvDUmQiu7ySw58W',
    label: 'HvjUNa...Sw58W',
    category: 'influencer',
    totalPnl: 242583,
    winRate: 0,
    totalTrades: 16326,
    favoriteTokens: ["pippin", "SKR", "ANSEM"],
    verified: false,
    description: 'Robinhood KOL. $242,583 P&L across 10 tokens.',
  },
  {
    id: '45',
    address: 'Hv4DsVJsZY1ACDfRNFLACLyzD5Y6yuwFffYj8N6Lo5f4',
    label: 'Hv4DsV...Lo5f4',
    category: 'influencer',
    totalPnl: 239053,
    winRate: 0,
    totalTrades: 2038,
    favoriteTokens: ["GAS", "SCAM", "PIGEON"],
    verified: false,
    description: 'Robinhood KOL. $239,053 P&L across 50 tokens.',
  },
  {
    id: '46',
    address: 'FVugAb5gWb6vz3zUppNoC5gWvbVA5xDGKnL9tTmTnxsU',
    label: 'FVug',
    category: 'influencer',
    totalPnl: 223050,
    winRate: 0,
    totalTrades: 796,
    favoriteTokens: ["SOLANGELES", "HANTA", "Franklin"],
    verified: false,
    description: 'Robinhood KOL. $223,050 P&L across 50 tokens.',
  },
  {
    id: '47',
    address: '3VCx8WYeP6dmWaUgChyvNEqTqaCn9bNDsYBgBVbHTZ68',
    label: 'UPNEXT',
    category: 'influencer',
    totalPnl: 183407,
    winRate: 0,
    totalTrades: 368,
    favoriteTokens: ["HODL", "NoLimit", "TripleT"],
    verified: false,
    description: 'Robinhood KOL. $183,407 P&L across 50 tokens.',
  },
  {
    id: '48',
    address: '6bQSN4d6anoTwnE6XDPGLA9RV8cqZPeNJro4iQUsWmso',
    label: 'wrld_sol',
    category: 'influencer',
    totalPnl: 153267,
    winRate: 0,
    totalTrades: 184,
    favoriteTokens: ["TripleT", "Buttcoin", "Jimothy"],
    verified: false,
    description: 'Robinhood KOL. $153,267 P&L across 50 tokens.',
  },
  {
    id: '49',
    address: 'AURAfARMAys9rF7RCpbcSPLt6jPhrzPT1CueXYnjGrVf',
    label: 'AURAfA...jGrVf',
    category: 'influencer',
    totalPnl: 152385,
    winRate: 0,
    totalTrades: 2193,
    favoriteTokens: ["Mountain", "EVA", "Lobstar"],
    verified: false,
    description: 'Robinhood KOL. $152,385 P&L across 50 tokens.',
  },
  {
    id: '50',
    address: '3XwyEYzxNDfZvTDQ64dDhdek1GDrykyNjfMv6FvNXZqm',
    label: '3XwyEY...NXZqm',
    category: 'influencer',
    totalPnl: 138066,
    winRate: 0,
    totalTrades: 227,
    favoriteTokens: ["PENGUIN", "Lobstar", "WORTHLESS"],
    verified: false,
    description: 'Robinhood KOL. $138,066 P&L across 50 tokens.',
  },
  {
    id: '51',
    address: '2DBwrNi5gU4PhsyZJMbGtcXcnU3KhAhSN9bbQFV5mDDU',
    label: '2DBwrN...5mDDU',
    category: 'influencer',
    totalPnl: 132525,
    winRate: 0,
    totalTrades: 5351,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $132,525 P&L across 1 tokens.',
  },
  {
    id: '52',
    address: 'GzdmCEKdHH9TpTA3xmkV8XKxHEQCDqqu8TMGULm2rB9x',
    label: 'GzdmCE...2rB9x',
    category: 'influencer',
    totalPnl: 128947,
    winRate: 0,
    totalTrades: 5265,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $128,947 P&L across 1 tokens.',
  },
  {
    id: '53',
    address: '9LAWxR1CDS1EyhkzT2AgoGxDmTGyyiicdoDjr2UgY6R3',
    label: '9LAWxR...gY6R3',
    category: 'influencer',
    totalPnl: 120729,
    winRate: 0,
    totalTrades: 4907,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $120,729 P&L across 1 tokens.',
  },
  {
    id: '54',
    address: 'J7nyPx4WBBon5t5jPVJyfLagdVPZYMTtYxTcuJsvdkWU',
    label: 'J7nyPx...vdkWU',
    category: 'influencer',
    totalPnl: 113931,
    winRate: 0,
    totalTrades: 202,
    favoriteTokens: ["testicle", "PsyopAnime", "STREAM"],
    verified: false,
    description: 'Robinhood KOL. $113,931 P&L across 50 tokens.',
  },
  {
    id: '55',
    address: '7a6GJv1FJPmZwEWceXduabVTpctd9uBT9kSxG6vDQAM4',
    label: '7a6G...QAM4',
    category: 'influencer',
    totalPnl: 4658874,
    winRate: 0,
    totalTrades: 1037,
    favoriteTokens: ["TRUMP", "ZEREBRO", "ai16z"],
    verified: false,
    description: 'Robinhood KOL. $4,658,874 P&L across 50 tokens.',
  },
  {
    id: '56',
    address: '9xaQ3jPuaRC5KaNkov7Lw6Bq1gKjRp4wD67v6pK1MdK1',
    label: '9xaQ3j...1MdK1',
    category: 'influencer',
    totalPnl: 2689737,
    winRate: 0,
    totalTrades: 1361,
    favoriteTokens: ["$WIF", "Bonk", "DITH"],
    verified: false,
    description: 'Robinhood KOL. $2,689,737 P&L across 50 tokens.',
  },
  {
    id: '57',
    address: 'A2B76kth3LZB7GK6dSzRcZBYNWsn2K6fCWyKVXBFqKx4',
    label: 'A2B76k...FqKx4',
    category: 'influencer',
    totalPnl: 2119457,
    winRate: 0,
    totalTrades: 497,
    favoriteTokens: ["TRUMP", "ZACHXBT", "nub"],
    verified: false,
    description: 'Robinhood KOL. $2,119,457 P&L across 50 tokens.',
  },
  {
    id: '58',
    address: '9XVWfqzavraezfvS38v8xcZepHYxcNKtnNMEKpPXEwTN',
    label: '9XVWfq...XEwTN',
    category: 'influencer',
    totalPnl: 1993962,
    winRate: 0,
    totalTrades: 1348,
    favoriteTokens: ["Ani", "TripleT", "GOR"],
    verified: false,
    description: 'Robinhood KOL. $1,993,962 P&L across 50 tokens.',
  },
  {
    id: '59',
    address: 'HyYNVYmnFmi87NsQqWzLJhUTPBKQUfgfhdbBa554nMFF',
    label: 'HyYN 50% WR 7d',
    category: 'influencer',
    totalPnl: 1875793,
    winRate: 0,
    totalTrades: 946,
    favoriteTokens: ["FART", "LEGS", "\ud83d\udca8"],
    verified: false,
    description: 'Robinhood KOL. $1,875,793 P&L across 50 tokens.',
  },
  {
    id: '60',
    address: '3BH2uRNcbVhCJNxoHqiwP8gXV69LmAtPxdaaRR9DzJ1a',
    label: '3BH2uR...DzJ1a',
    category: 'influencer',
    totalPnl: 1391740,
    winRate: 0,
    totalTrades: 2888,
    favoriteTokens: ["Fartcoin", "IO", "TRUMP"],
    verified: false,
    description: 'Robinhood KOL. $1,391,740 P&L across 50 tokens.',
  },
  {
    id: '61',
    address: 'EPKrfFVt2CoaUnCo8eMauH3PEsK3rwyPQefxGd1zEi8m',
    label: 'EPKrfF...zEi8m',
    category: 'influencer',
    totalPnl: 946560,
    winRate: 0,
    totalTrades: 432,
    favoriteTokens: ["MELANIA", "TRUMP", "YZY"],
    verified: false,
    description: 'Robinhood KOL. $946,560 P&L across 50 tokens.',
  },
  {
    id: '62',
    address: 'EFqaGUqEtoSqz4FZF7Kgf9p8VYAH8WN9vqrkF9E4nx2K',
    label: 'EFqaGU...4nx2K',
    category: 'influencer',
    totalPnl: 790608,
    winRate: 0,
    totalTrades: 383,
    favoriteTokens: ["META", "KOHAI", "DEBT"],
    verified: false,
    description: 'Robinhood KOL. $790,608 P&L across 50 tokens.',
  },
  {
    id: '63',
    address: 'BuhkHhM3j4viF71pMTd23ywxPhF35LUnc2QCLAvUxCdW',
    label: 'BuhkHh...UxCdW',
    category: 'influencer',
    totalPnl: 720099,
    winRate: 0,
    totalTrades: 1015,
    favoriteTokens: ["memecoin", "Punch", "LABUBU"],
    verified: false,
    description: 'Robinhood KOL. $720,099 P&L across 50 tokens.',
  },
  {
    id: '64',
    address: 'EPi6pYo9kDvwoqcc5S5ok8oj1LEB3n3Zfns64u1CA4mS',
    label: 'EPi6pY...CA4mS',
    category: 'influencer',
    totalPnl: 709580,
    winRate: 0,
    totalTrades: 1451,
    favoriteTokens: ["SGL", "FARMCOIN", "LIBRA"],
    verified: false,
    description: 'Robinhood KOL. $709,580 P&L across 50 tokens.',
  },
  {
    id: '65',
    address: '7yXdiQ7ufCLKb1UUEPXuaqpwnodbVqmmVbH59qwFSB1x',
    label: '7yXdiQ...FSB1x',
    category: 'influencer',
    totalPnl: 666616,
    winRate: 0,
    totalTrades: 8136,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $666,616 P&L across 1 tokens.',
  },
  {
    id: '66',
    address: '3U6AdFFfrDJ6PbwJCi21vYtayKgB8gUUTBBpcpsaJ9G1',
    label: '3U6AdF...aJ9G1',
    category: 'influencer',
    totalPnl: 657081,
    winRate: 0,
    totalTrades: 7939,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $657,081 P&L across 1 tokens.',
  },
  {
    id: '67',
    address: '7aMgK5L4qEQ8Nyv6ZzhZi2B82NSSRnwb2NGJnNagA46D',
    label: '7aMgK5...gA46D',
    category: 'influencer',
    totalPnl: 624992,
    winRate: 0,
    totalTrades: 1120,
    favoriteTokens: ["TripleT", "67", "neet"],
    verified: false,
    description: 'Robinhood KOL. $624,992 P&L across 50 tokens.',
  },
  {
    id: '68',
    address: '8sh7DVftVU2dEbyUt7KoZs9KngXx95Gvz2DRk3tuKAJY',
    label: '8sh7DV...uKAJY',
    category: 'influencer',
    totalPnl: 612970,
    winRate: 0,
    totalTrades: 8184,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $612,970 P&L across 1 tokens.',
  },
  {
    id: '69',
    address: '4vixhVdCKpekJFyzYN6ABDmrh4aJKGSZpSqURXfB6ZyC',
    label: '4vixhV...B6ZyC',
    category: 'influencer',
    totalPnl: 612576,
    winRate: 0,
    totalTrades: 8050,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $612,576 P&L across 1 tokens.',
  },
  {
    id: '70',
    address: '6Nwh13DMMP6xLuMPeLbt14o2KdbiiXYETcCLWjYWaV7L',
    label: '6Nwh13...WaV7L',
    category: 'influencer',
    totalPnl: 533889,
    winRate: 0,
    totalTrades: 556,
    favoriteTokens: ["pippin", "Punch", "WAR"],
    verified: false,
    description: 'Robinhood KOL. $533,889 P&L across 50 tokens.',
  },
  {
    id: '71',
    address: 'Dk4na3gi8HYrrnFDcRgVfET23Ltm7AxbzvPpGyHaXwQJ',
    label: '0xuberM',
    category: 'influencer',
    totalPnl: 515108,
    winRate: 0,
    totalTrades: 899,
    favoriteTokens: ["unc", "Buttcoin", "Goblin"],
    verified: false,
    description: 'Robinhood KOL. $515,108 P&L across 50 tokens.',
  },
  {
    id: '72',
    address: 'Bn3BSYQKLa1aMoeLLUF4ZEsqBAbP3evsxiGBSWvaCY1k',
    label: 'Bn3BSY...aCY1k',
    category: 'influencer',
    totalPnl: 503007,
    winRate: 0,
    totalTrades: 6969,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $503,007 P&L across 1 tokens.',
  },
  {
    id: '73',
    address: '6WCkVkJFig5FUoQjbH3sm24bQLrTcPbvZHSxrkqu3kPv',
    label: '6WCkVk...u3kPv',
    category: 'influencer',
    totalPnl: 502793,
    winRate: 0,
    totalTrades: 2004,
    favoriteTokens: ["TripleT", "Bagwork", "Samara"],
    verified: false,
    description: 'Robinhood KOL. $502,793 P&L across 50 tokens.',
  },
  {
    id: '74',
    address: '4Y84ZayuVutuW2e1Lq8qfq5JYwYkTn8CtutmZs3jW8oM',
    label: '4Y84Za...jW8oM',
    category: 'influencer',
    totalPnl: 491653,
    winRate: 0,
    totalTrades: 107,
    favoriteTokens: ["USDG", "kySOL", "USX"],
    verified: false,
    description: 'Robinhood KOL. $491,653 P&L across 5 tokens.',
  },
  {
    id: '75',
    address: '6jco9JKp5udbGJ8qPB1eCqjuXj7vcTzGpW9926ouDzAs',
    label: '6jco9J...uDzAs',
    category: 'influencer',
    totalPnl: 489479,
    winRate: 0,
    totalTrades: 7669,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $489,479 P&L across 1 tokens.',
  },
  {
    id: '76',
    address: 'AcWAURKHUXHF3zEqR6fje5bGJHdsfd1SyLQmbXqEtf8Y',
    label: 'AcWAUR...Etf8Y',
    category: 'influencer',
    totalPnl: 484552,
    winRate: 0,
    totalTrades: 576,
    favoriteTokens: ["Punch", "KLED", "AVO"],
    verified: false,
    description: 'Robinhood KOL. $484,552 P&L across 50 tokens.',
  },
  {
    id: '77',
    address: '3v29xG5e1yjgWkokPAaKBhwxbF5DzJokMQVvQbecuYAV',
    label: 'Cex buys',
    category: 'influencer',
    totalPnl: 444245,
    winRate: 0,
    totalTrades: 603,
    favoriteTokens: ["DAFLE"],
    verified: false,
    description: 'Robinhood KOL. $444,245 P&L across 1 tokens.',
  },
  {
    id: '78',
    address: 'C21R6y1fqFUNCEzNJgjVcEnjTE2y6Cq7GWLfZzkbBm7a',
    label: 'C21R...Bm7a',
    category: 'influencer',
    totalPnl: 437809,
    winRate: 0,
    totalTrades: 1048,
    favoriteTokens: ["SKR", "GAS", "Punch"],
    verified: false,
    description: 'Robinhood KOL. $437,809 P&L across 50 tokens.',
  },
  {
    id: '79',
    address: 'E1oQG6gZsdSqoLcvW8pKWsxh5W4bd6GQYL6xyhRw3Lg8',
    label: 'E1oQG6...w3Lg8',
    category: 'influencer',
    totalPnl: 430893,
    winRate: 0,
    totalTrades: 9664,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $430,893 P&L across 1 tokens.',
  },
  {
    id: '80',
    address: '4F1XUgtstYYbKQSdURg4bhbHEGXBmNFYJYhQEjw2ZLto',
    label: '4F1XUg...2ZLto',
    category: 'influencer',
    totalPnl: 383919,
    winRate: 0,
    totalTrades: 1117,
    favoriteTokens: ["Punch", "Cupsey", "BioLLM"],
    verified: false,
    description: 'Robinhood KOL. $383,919 P&L across 50 tokens.',
  },
  {
    id: '81',
    address: '2jjgBEwQqhUXRPjSqGqwsWCkqgRsZ7MkT3kTeWJJ8e7Q',
    label: '2jjgBE...J8e7Q',
    category: 'influencer',
    totalPnl: 366766,
    winRate: 0,
    totalTrades: 1425,
    favoriteTokens: ["PENGUIN", "Punch", "ELIZA TOWN"],
    verified: false,
    description: 'Robinhood KOL. $366,766 P&L across 50 tokens.',
  },
  {
    id: '82',
    address: 'FUDjTfP7oRipn317ben99P3hjEGDgwKTfPm2QxGwQd78',
    label: 'FUDjTf...wQd78',
    category: 'influencer',
    totalPnl: 343819,
    winRate: 0,
    totalTrades: 952,
    favoriteTokens: ["Punch", "LIZARD", "Cope"],
    verified: false,
    description: 'Robinhood KOL. $343,819 P&L across 50 tokens.',
  },
  {
    id: '83',
    address: '9wyzq1yJiBgesmGeKtycbir2B3TEoJJQvdCBrzNebJq9',
    label: '9wyzq1...ebJq9',
    category: 'influencer',
    totalPnl: 326956,
    winRate: 0,
    totalTrades: 558,
    favoriteTokens: ["Punch", "CARDS", "SKR"],
    verified: false,
    description: 'Robinhood KOL. $326,956 P&L across 40 tokens.',
  },
  {
    id: '84',
    address: '9dbcLC76Cr32kkSt2ayEzkYxxptwtkyAnSYNUsnnzK8A',
    label: 'XXX',
    category: 'influencer',
    totalPnl: 287016,
    winRate: 0,
    totalTrades: 768,
    favoriteTokens: ["Buttcoin", "Shellraiser", "FWOG"],
    verified: false,
    description: 'Robinhood KOL. $287,016 P&L across 50 tokens.',
  },
  {
    id: '85',
    address: 'FZ8ofuKKQbZ6QKRGYb75hD2Un56MKJzF6zErpcLn3Cma',
    label: 'FZ8ofu...n3Cma',
    category: 'influencer',
    totalPnl: 284141,
    winRate: 0,
    totalTrades: 787,
    favoriteTokens: ["Punch", "TripleT", "KINS"],
    verified: false,
    description: 'Robinhood KOL. $284,141 P&L across 50 tokens.',
  },
  {
    id: '86',
    address: 'AcoNeFQsTPYs7ZrH8RMWaxxGJTTQJJ4H5aTXmptaz5UK',
    label: 'AcoNeF...az5UK',
    category: 'influencer',
    totalPnl: 277415,
    winRate: 0,
    totalTrades: 675,
    favoriteTokens: ["Jotchua", "Chiikawa", "GTAVI"],
    verified: false,
    description: 'Robinhood KOL. $277,415 P&L across 50 tokens.',
  },
  {
    id: '87',
    address: 'FKq4DRBrtVwaKsYeAWRnYxRKav5n7ScxbGzkaKn3sgEH',
    label: 'FKq4DR...3sgEH',
    category: 'influencer',
    totalPnl: 268783,
    winRate: 0,
    totalTrades: 565,
    favoriteTokens: ["POPCAT", "USELESS", "Fartcoin"],
    verified: false,
    description: 'Robinhood KOL. $268,783 P&L across 50 tokens.',
  },
  {
    id: '88',
    address: 'B5eHbv7xrBhjvA2NFYr7hP8LDwJmEVdnfDzVkEKUDXqc',
    label: 'B5eHbv...UDXqc',
    category: 'influencer',
    totalPnl: 263932,
    winRate: 0,
    totalTrades: 1712,
    favoriteTokens: ["Lobstar", "ASTEROID", "Punch"],
    verified: false,
    description: 'Robinhood KOL. $263,932 P&L across 50 tokens.',
  },
  {
    id: '89',
    address: '6mWEJG9LoRdto8TwTdZxmnJpkXpTsEerizcGiCNZvzXd',
    label: 'slingoorio.sol',
    category: 'influencer',
    totalPnl: 254347,
    winRate: 0,
    totalTrades: 8138,
    favoriteTokens: ["LMAO!", "WOJAK", "SPSC"],
    verified: false,
    description: 'Robinhood KOL. $254,347 P&L across 50 tokens.',
  },
  {
    id: '90',
    address: 'DaUBRKnAjuqzozUjkH4QuVJUJiSmrbnLbCeqAgwA6dGF',
    label: 'DaUBRK...A6dGF',
    category: 'influencer',
    totalPnl: 254294,
    winRate: 0,
    totalTrades: 908,
    favoriteTokens: ["PENGUIN", "Chonketha", "WhiteHouse"],
    verified: false,
    description: 'Robinhood KOL. $254,294 P&L across 50 tokens.',
  },
  {
    id: '91',
    address: 'HvjUNaVTHZqZ2AqnJJPGJ3GJkJhhbvvDUmQiu7ySw58W',
    label: 'HvjUNa...Sw58W',
    category: 'influencer',
    totalPnl: 242583,
    winRate: 0,
    totalTrades: 16326,
    favoriteTokens: ["pippin", "SKR", "ANSEM"],
    verified: false,
    description: 'Robinhood KOL. $242,583 P&L across 10 tokens.',
  },
  {
    id: '92',
    address: 'Hv4DsVJsZY1ACDfRNFLACLyzD5Y6yuwFffYj8N6Lo5f4',
    label: 'Hv4DsV...Lo5f4',
    category: 'influencer',
    totalPnl: 239053,
    winRate: 0,
    totalTrades: 2038,
    favoriteTokens: ["GAS", "SCAM", "PIGEON"],
    verified: false,
    description: 'Robinhood KOL. $239,053 P&L across 50 tokens.',
  },
  {
    id: '93',
    address: '9XR3dcvd9YgRyo2TeKefJUh1eBzy3rxjEajeq6nWDZor',
    label: '9XR3dc...WDZor',
    category: 'influencer',
    totalPnl: 233192,
    winRate: 0,
    totalTrades: 806,
    favoriteTokens: ["Punch", "KIMCHI", "Flufy"],
    verified: false,
    description: 'Robinhood KOL. $233,192 P&L across 50 tokens.',
  },
  {
    id: '94',
    address: 'FVugAb5gWb6vz3zUppNoC5gWvbVA5xDGKnL9tTmTnxsU',
    label: 'FVug',
    category: 'influencer',
    totalPnl: 223050,
    winRate: 0,
    totalTrades: 796,
    favoriteTokens: ["SOLANGELES", "HANTA", "Franklin"],
    verified: false,
    description: 'Robinhood KOL. $223,050 P&L across 50 tokens.',
  },
  {
    id: '95',
    address: '2gjDmkFTsByCebzLfVnrksH7AhghCE1t6u2giw9gAdBm',
    label: '2gjDmk...gAdBm',
    category: 'influencer',
    totalPnl: 215888,
    winRate: 0,
    totalTrades: 1268,
    favoriteTokens: ["Punch", "ANSEM", "BURNIE"],
    verified: false,
    description: 'Robinhood KOL. $215,888 P&L across 50 tokens.',
  },
  {
    id: '96',
    address: '5nP2D2ff6FShqgLR4syNWDfxgeYwPvDbT4AfZdGRFjf7',
    label: '5nP2D2...RFjf7',
    category: 'influencer',
    totalPnl: 201463,
    winRate: 0,
    totalTrades: 1108,
    favoriteTokens: ["Punch", "manlet", "TAILWIND"],
    verified: false,
    description: 'Robinhood KOL. $201,463 P&L across 50 tokens.',
  },
  {
    id: '97',
    address: '8TGPZxspVeLFebAvqYBsTomubJyMWDHbNVsqVZfm1H9u',
    label: '8TGPZx...m1H9u',
    category: 'influencer',
    totalPnl: 186619,
    winRate: 0,
    totalTrades: 907,
    favoriteTokens: ["Punch", "DONT", "ZHC"],
    verified: false,
    description: 'Robinhood KOL. $186,619 P&L across 50 tokens.',
  },
  {
    id: '98',
    address: '3VCx8WYeP6dmWaUgChyvNEqTqaCn9bNDsYBgBVbHTZ68',
    label: 'UPNEXT',
    category: 'influencer',
    totalPnl: 183407,
    winRate: 0,
    totalTrades: 368,
    favoriteTokens: ["HODL", "NoLimit", "TripleT"],
    verified: false,
    description: 'Robinhood KOL. $183,407 P&L across 50 tokens.',
  },
  {
    id: '99',
    address: 'GiJzJjBaeAZqcP4NTz9xjAhk4ZMau1tfgViumsKZ5xw1',
    label: 'GiJzJj...Z5xw1',
    category: 'influencer',
    totalPnl: 170634,
    winRate: 0,
    totalTrades: 232,
    favoriteTokens: ["Punch", "ANI", "MARS"],
    verified: false,
    description: 'Robinhood KOL. $170,634 P&L across 50 tokens.',
  },
  {
    id: '100',
    address: 'HJXa57WZozLegR8rvUbHAZK1LPUqjMyjvkdoHfXE8dNH',
    label: 'HJXa57...E8dNH',
    category: 'influencer',
    totalPnl: 155091,
    winRate: 0,
    totalTrades: 436,
    favoriteTokens: ["maxxing", "RHD", "clark"],
    verified: false,
    description: 'Robinhood KOL. $155,091 P&L across 50 tokens.',
  },
  {
    id: '101',
    address: '6bQSN4d6anoTwnE6XDPGLA9RV8cqZPeNJro4iQUsWmso',
    label: 'wrld_sol',
    category: 'influencer',
    totalPnl: 153267,
    winRate: 0,
    totalTrades: 184,
    favoriteTokens: ["TripleT", "Buttcoin", "Jimothy"],
    verified: false,
    description: 'Robinhood KOL. $153,267 P&L across 50 tokens.',
  },
  {
    id: '102',
    address: 'AURAfARMAys9rF7RCpbcSPLt6jPhrzPT1CueXYnjGrVf',
    label: 'AURAfA...jGrVf',
    category: 'influencer',
    totalPnl: 152385,
    winRate: 0,
    totalTrades: 2193,
    favoriteTokens: ["Mountain", "EVA", "Lobstar"],
    verified: false,
    description: 'Robinhood KOL. $152,385 P&L across 50 tokens.',
  },
  {
    id: '103',
    address: 'J1nQS7RXVSRij4S5AUdhFYYwwWxT1fdBtmJQvSfhywic',
    label: 'J1nQS7...hywic',
    category: 'influencer',
    totalPnl: 152183,
    winRate: 0,
    totalTrades: 570,
    favoriteTokens: ["Punch", "kitkat", "BITTY"],
    verified: false,
    description: 'Robinhood KOL. $152,183 P&L across 50 tokens.',
  },
  {
    id: '104',
    address: '3XwyEYzxNDfZvTDQ64dDhdek1GDrykyNjfMv6FvNXZqm',
    label: '3XwyEY...NXZqm',
    category: 'influencer',
    totalPnl: 138066,
    winRate: 0,
    totalTrades: 227,
    favoriteTokens: ["PENGUIN", "Lobstar", "WORTHLESS"],
    verified: false,
    description: 'Robinhood KOL. $138,066 P&L across 50 tokens.',
  },
  {
    id: '105',
    address: '2DBwrNi5gU4PhsyZJMbGtcXcnU3KhAhSN9bbQFV5mDDU',
    label: '2DBwrN...5mDDU',
    category: 'influencer',
    totalPnl: 132525,
    winRate: 0,
    totalTrades: 5351,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $132,525 P&L across 1 tokens.',
  },
  {
    id: '106',
    address: 'GzdmCEKdHH9TpTA3xmkV8XKxHEQCDqqu8TMGULm2rB9x',
    label: 'GzdmCE...2rB9x',
    category: 'influencer',
    totalPnl: 128947,
    winRate: 0,
    totalTrades: 5265,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $128,947 P&L across 1 tokens.',
  },
  {
    id: '107',
    address: 'FDhPi7nTwHe5DVjkdLcjeH2JajiNDG3NAbwiccnYkcdh',
    label: 'FDhPi7...Ykcdh',
    category: 'influencer',
    totalPnl: 128751,
    winRate: 0,
    totalTrades: 4133,
    favoriteTokens: ["BURNIE", "world", "testicle"],
    verified: false,
    description: 'Robinhood KOL. $128,751 P&L across 50 tokens.',
  },
  {
    id: '108',
    address: '9LAWxR1CDS1EyhkzT2AgoGxDmTGyyiicdoDjr2UgY6R3',
    label: '9LAWxR...gY6R3',
    category: 'influencer',
    totalPnl: 120729,
    winRate: 0,
    totalTrades: 4907,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $120,729 P&L across 1 tokens.',
  },
  {
    id: '109',
    address: 'FQHcrTMbxGhK39z9w5iM6UJPNER4BcShdxYiWCDBvzLx',
    label: 'FQHcrT...BvzLx',
    category: 'influencer',
    totalPnl: 115243,
    winRate: 0,
    totalTrades: 775,
    favoriteTokens: ["Punch", "ELON", "OPENCLAW"],
    verified: false,
    description: 'Robinhood KOL. $115,243 P&L across 50 tokens.',
  },
  {
    id: '110',
    address: 'J7nyPx4WBBon5t5jPVJyfLagdVPZYMTtYxTcuJsvdkWU',
    label: 'J7nyPx...vdkWU',
    category: 'influencer',
    totalPnl: 113931,
    winRate: 0,
    totalTrades: 202,
    favoriteTokens: ["testicle", "PsyopAnime", "STREAM"],
    verified: false,
    description: 'Robinhood KOL. $113,931 P&L across 50 tokens.',
  },
  {
    id: '111',
    address: 'CVJZ63J864vF4Pf8Z9zgoTXVs8ymYzPmkgVoms8UtEMq',
    label: 'CVJZ63...UtEMq',
    category: 'influencer',
    totalPnl: 113369,
    winRate: 0,
    totalTrades: 3421,
    favoriteTokens: ["ANUS", "DNA", "CAT"],
    verified: false,
    description: 'Robinhood KOL. $113,369 P&L across 50 tokens.',
  },
  {
    id: '112',
    address: 'Cv9d9yYD9G49Rwo3cLc3kLyGo9ZeBnR7p7QdGd6yaTxc',
    label: 'Cv9d9y...yaTxc',
    category: 'influencer',
    totalPnl: 112279,
    winRate: 0,
    totalTrades: 1148,
    favoriteTokens: ["SPSN", "KIND", "MLG"],
    verified: false,
    description: 'Robinhood KOL. $112,279 P&L across 50 tokens.',
  },
  {
    id: '113',
    address: '5fjZatNnqmWixUtycekodpsaNHCHVe48oBzaLbV4kXRL',
    label: '5fjZat...4kXRL',
    category: 'influencer',
    totalPnl: 107997,
    winRate: 0,
    totalTrades: 601,
    favoriteTokens: ["maxxing", "Caricature", "KIMCHI"],
    verified: false,
    description: 'Robinhood KOL. $107,997 P&L across 50 tokens.',
  },
  {
    id: '114',
    address: 'D8DDd9o7JNikvggZdEeE9ojwioUsRcbvDm8UFfFa7eDw',
    label: 'D8DDd9...a7eDw',
    category: 'influencer',
    totalPnl: 105585,
    winRate: 0,
    totalTrades: 1141,
    favoriteTokens: ["LION", "SPSN", "TripleT"],
    verified: false,
    description: 'Robinhood KOL. $105,585 P&L across 50 tokens.',
  },
  {
    id: '115',
    address: 'Bshg5QoMMnduF6zPdpHY9C2AauZP1avPC7xxJbB3SYpW',
    label: 'Bshg5Q...3SYpW',
    category: 'influencer',
    totalPnl: 103698,
    winRate: 0,
    totalTrades: 1173,
    favoriteTokens: ["Lobstar", "Buttcoin", "Shrimp"],
    verified: false,
    description: 'Robinhood KOL. $103,698 P&L across 50 tokens.',
  },
  {
    id: '116',
    address: 'A7K7doXf75Rws2oBipXGBWhHJjKdhYFZeyuFGU74jtKk',
    label: 'A7K7do...4jtKk',
    category: 'influencer',
    totalPnl: 102873,
    winRate: 0,
    totalTrades: 777,
    favoriteTokens: ["TJR", "zero", "BOP"],
    verified: false,
    description: 'Robinhood KOL. $102,873 P&L across 50 tokens.',
  },
  {
    id: '117',
    address: 'FNa6k1kcZaos5Hb2UriBtcmBrWBA5o1UizoURd52Zk1i',
    label: 'FNa6k1...2Zk1i',
    category: 'influencer',
    totalPnl: 94781,
    winRate: 0,
    totalTrades: 234,
    favoriteTokens: ["USEFUL", "maxxing", "ASSDAQ"],
    verified: false,
    description: 'Robinhood KOL. $94,781 P&L across 50 tokens.',
  },
  {
    id: '118',
    address: '3FSCAGkKJL9mj84HaLriHyEqUJqPXnHnRMMyCpj9z9xf',
    label: '3FSCAG...9z9xf',
    category: 'influencer',
    totalPnl: 93840,
    winRate: 0,
    totalTrades: 4646,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $93,840 P&L across 1 tokens.',
  },
  {
    id: '119',
    address: '6Q3JsVPvxR5L7iZkGcEAZ9aRVz3XkPzFE4eJD63iXYoG',
    label: '6Q3JsV...iXYoG',
    category: 'influencer',
    totalPnl: 88951,
    winRate: 0,
    totalTrades: 523,
    favoriteTokens: ["Punch", "Maman", "ASOL"],
    verified: false,
    description: 'Robinhood KOL. $88,951 P&L across 6 tokens.',
  },
  {
    id: '120',
    address: '5Mk8MG41VqYMwNrnSsWPN11XCwXuwRVWfDP3Xh1n4ppf',
    label: '5Mk8MG...n4ppf',
    category: 'influencer',
    totalPnl: 85958,
    winRate: 0,
    totalTrades: 1437,
    favoriteTokens: ["Punch", "Slurmit", "Aslan"],
    verified: false,
    description: 'Robinhood KOL. $85,958 P&L across 50 tokens.',
  },
  {
    id: '121',
    address: 'HZZ479dTmfQtaWkC5TFajVUJ5tEqqXxePeJYKLrPu5vn',
    label: 'HZZ479...Pu5vn',
    category: 'influencer',
    totalPnl: 81745,
    winRate: 0,
    totalTrades: 4389,
    favoriteTokens: ["MEDIA", "STREAM", "JIHAD"],
    verified: false,
    description: 'Robinhood KOL. $81,745 P&L across 50 tokens.',
  },
  {
    id: '122',
    address: 'A4MB7wKjaFQzh2CkQHQ1cUmeJDRekhM23GRwATGJFT4g',
    label: 'A4MB7w...JFT4g',
    category: 'influencer',
    totalPnl: 80136,
    winRate: 0,
    totalTrades: 1169,
    favoriteTokens: ["Lobstar", "Shrimp", "ELON"],
    verified: false,
    description: 'Robinhood KOL. $80,136 P&L across 50 tokens.',
  },
  {
    id: '123',
    address: 'FXj7ZPV7J7xtoFJNeQA2mrTp3Xn3Vo4NyWg9gh33AEwA',
    label: 'FXj7ZP...3AEwA',
    category: 'influencer',
    totalPnl: 79673,
    winRate: 0,
    totalTrades: 4239,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $79,673 P&L across 1 tokens.',
  },
  {
    id: '124',
    address: '4Dk8hCg27ZLun5DHkfoYX4RZLk8bKirWZxEtWqWd6TBp',
    label: '4Dk8hC...d6TBp',
    category: 'influencer',
    totalPnl: 79045,
    winRate: 0,
    totalTrades: 5507,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $79,045 P&L across 1 tokens.',
  },
  {
    id: '125',
    address: 'U2iC7HRpi9yijEbnnU7j7z1NaX4ZQAs6hBhzMRHjfx8',
    label: 'U2iC7H...Hjfx8',
    category: 'influencer',
    totalPnl: 75229,
    winRate: 0,
    totalTrades: 363,
    favoriteTokens: ["Punch", "Clawrl", "PERC"],
    verified: false,
    description: 'Robinhood KOL. $75,229 P&L across 50 tokens.',
  },
  {
    id: '126',
    address: '2vm2EBT9SKT6JYCdXCdJabvRjsp22QwZfHaFczGB9MeV',
    label: '2vm2EB...B9MeV',
    category: 'influencer',
    totalPnl: 74701,
    winRate: 0,
    totalTrades: 6315,
    favoriteTokens: ["maxxing", "Tokabu", "MLG"],
    verified: false,
    description: 'Robinhood KOL. $74,701 P&L across 50 tokens.',
  },
  {
    id: '127',
    address: '7SRmDg1VRWNQnzhzR5LCfngKVML6iaN8uFE6iRV8XjZn',
    label: '7SRmDg...8XjZn',
    category: 'influencer',
    totalPnl: 73604,
    winRate: 0,
    totalTrades: 223,
    favoriteTokens: ["Lobstar", "RALPH", "MOSS"],
    verified: false,
    description: 'Robinhood KOL. $73,604 P&L across 37 tokens.',
  },
  {
    id: '128',
    address: '7qZ3hMXRXCveKs3LR2HJBAHBofrWAGDQu4pZ5F1VyJYN',
    label: '7qZ3hM...VyJYN',
    category: 'influencer',
    totalPnl: 72672,
    winRate: 0,
    totalTrades: 424,
    favoriteTokens: ["Punch", "CHIBI", "PIGEON"],
    verified: false,
    description: 'Robinhood KOL. $72,672 P&L across 50 tokens.',
  },
  {
    id: '129',
    address: 'HMJvTYEFXGLEV4wDqMr76bswpYRiHWZS349Gue4KYb28',
    label: 'HMJvTY...KYb28',
    category: 'influencer',
    totalPnl: 70183,
    winRate: 0,
    totalTrades: 549,
    favoriteTokens: ["Jotchua", "maxxing", "febu"],
    verified: false,
    description: 'Robinhood KOL. $70,183 P&L across 50 tokens.',
  },
  {
    id: '130',
    address: '4VsQ2aHE7ZeekbjjiwMHPL9qS4Rck4TFyBgrbDj3ez12',
    label: '4VsQ2a...3ez12',
    category: 'influencer',
    totalPnl: 67532,
    winRate: 0,
    totalTrades: 538,
    favoriteTokens: ["maxxing", "POKE", "SYFR"],
    verified: false,
    description: 'Robinhood KOL. $67,532 P&L across 50 tokens.',
  },
  {
    id: '131',
    address: '62HYfG7gxngCNBZWYhmiRuaepqXZN82k12xaGCniKJUt',
    label: '62HYfG...iKJUt',
    category: 'influencer',
    totalPnl: 66710,
    winRate: 0,
    totalTrades: 4018,
    favoriteTokens: ["maxxing", "LOOM"],
    verified: false,
    description: 'Robinhood KOL. $66,710 P&L across 50 tokens.',
  },
  {
    id: '132',
    address: 'AKwrDPR5GNtjwTnHd1FHhzgaADcajvqKJ54zRieAYKgx',
    label: 'AKwrDP...AYKgx',
    category: 'influencer',
    totalPnl: 66499,
    winRate: 0,
    totalTrades: 465,
    favoriteTokens: ["maxxing", "Sybau", "MESSI"],
    verified: false,
    description: 'Robinhood KOL. $66,499 P&L across 50 tokens.',
  },
  {
    id: '133',
    address: '6gMGbBHdRXiNR9YYXFVdTXz3WZyQu8CR54uzpTWxPPKt',
    label: '6gMGbB...xPPKt',
    category: 'influencer',
    totalPnl: 65620,
    winRate: 0,
    totalTrades: 288,
    favoriteTokens: ["HANTA", "Punch", "TJR"],
    verified: false,
    description: 'Robinhood KOL. $65,620 P&L across 50 tokens.',
  },
  {
    id: '134',
    address: 'HNpS5vThmTA8z7nBsB9XZmwYTNxuAPu8duuRKNxovDoV',
    label: 'HNpS5v...ovDoV',
    category: 'influencer',
    totalPnl: 65332,
    winRate: 0,
    totalTrades: 184,
    favoriteTokens: ["PENGUIN", "LIZARD", "FKH"],
    verified: false,
    description: 'Robinhood KOL. $65,332 P&L across 50 tokens.',
  },
  {
    id: '135',
    address: 'HxyvuaS98ubKUQM9DkoHjQn6kfU6tNM5PoKcwcQivmDD',
    label: 'Hxyvua...ivmDD',
    category: 'influencer',
    totalPnl: 63901,
    winRate: 0,
    totalTrades: 1527,
    favoriteTokens: ["SOLCEX", "CLAP", "aircoin"],
    verified: false,
    description: 'Robinhood KOL. $63,901 P&L across 50 tokens.',
  },
  {
    id: '136',
    address: 'Fk9sRh5fRhetPNHLixGemXjtJziJDtqB23mGJ3etdFtD',
    label: 'Fk9sRh...tdFtD',
    category: 'influencer',
    totalPnl: 62529,
    winRate: 0,
    totalTrades: 274,
    favoriteTokens: ["DUNA", "maxxing", "CLAW"],
    verified: false,
    description: 'Robinhood KOL. $62,529 P&L across 50 tokens.',
  },
  {
    id: '137',
    address: '9yYoY1t2752eh5T3W6Ckk6uFGp3e9R6J24NqqntTWDyU',
    label: '9yYoY1...TWDyU',
    category: 'influencer',
    totalPnl: 60817,
    winRate: 0,
    totalTrades: 474,
    favoriteTokens: ["ORAMAMA", "COCO", "RIZZTER"],
    verified: false,
    description: 'Robinhood KOL. $60,817 P&L across 50 tokens.',
  },
  {
    id: '138',
    address: '3tJ3k4Am1VzSZGGoMYTf1YhSHzQRjetNHbrWmUsbmmPN',
    label: '3tJ3k4...bmmPN',
    category: 'influencer',
    totalPnl: 60349,
    winRate: 0,
    totalTrades: 2164,
    favoriteTokens: ["SONIC", "gork", "jellyjelly"],
    verified: false,
    description: 'Robinhood KOL. $60,349 P&L across 50 tokens.',
  },
  {
    id: '139',
    address: '6gkboPaSKHfmqRkNcZTZX6zqrJdQJ9PDUSdPbvxa2n9n',
    label: '6gkboP...a2n9n',
    category: 'influencer',
    totalPnl: 59520,
    winRate: 0,
    totalTrades: 142,
    favoriteTokens: ["FUN", "AMELIA", "gork"],
    verified: false,
    description: 'Robinhood KOL. $59,520 P&L across 50 tokens.',
  },
  {
    id: '140',
    address: 'EbKQsCdFQQAGdwjR9VFxhZrM361wfnyb124HGJRXA55G',
    label: 'EbKQsC...XA55G',
    category: 'influencer',
    totalPnl: 58058,
    winRate: 0,
    totalTrades: 1156,
    favoriteTokens: ["Lobstar", "COPPERINU", "butthole"],
    verified: false,
    description: 'Robinhood KOL. $58,058 P&L across 50 tokens.',
  },
  {
    id: '141',
    address: 'CTcFhZyvtZ667yf83rZXV2XgenJPwnUVGzGX4u3iQH7M',
    label: 'CTcFhZ...iQH7M',
    category: 'influencer',
    totalPnl: 57039,
    winRate: 0,
    totalTrades: 6531,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $57,039 P&L across 1 tokens.',
  },
  {
    id: '142',
    address: '8531nEwD3o66mWYDTCBveAYVsYbFn9qpL43jXS4exasT',
    label: '8531nE...exasT',
    category: 'influencer',
    totalPnl: 55669,
    winRate: 0,
    totalTrades: 333,
    favoriteTokens: ["Lobstar", "Pixel", "BEE"],
    verified: false,
    description: 'Robinhood KOL. $55,669 P&L across 50 tokens.',
  },
  {
    id: '143',
    address: '6YEbs5xqYjNk7qiz94Bn8heYFu9CdAfbcn3sdrJ6j2QY',
    label: '6YEbs5...6j2QY',
    category: 'influencer',
    totalPnl: 54300,
    winRate: 0,
    totalTrades: 316,
    favoriteTokens: ["LUMEN", "MEMELESS", "pinheads"],
    verified: false,
    description: 'Robinhood KOL. $54,300 P&L across 50 tokens.',
  },
  {
    id: '144',
    address: 'EviWc5PDgEYQURUg7KFtBKULSzoNT8o33oJzS6Ru7eYj',
    label: 'EviWc5...u7eYj',
    category: 'influencer',
    totalPnl: 53638,
    winRate: 0,
    totalTrades: 645,
    favoriteTokens: ["maxxing", "CHANCE", "abcdefg"],
    verified: false,
    description: 'Robinhood KOL. $53,638 P&L across 50 tokens.',
  },
  {
    id: '145',
    address: '9y4fgeyybAZ5R4JccdxLQo8K1MSZWiSUfcqvwZp2LVMi',
    label: '9y4fge...2LVMi',
    category: 'influencer',
    totalPnl: 53501,
    winRate: 0,
    totalTrades: 3453,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $53,501 P&L across 1 tokens.',
  },
  {
    id: '146',
    address: 'HfAiupvsLBQTFT19gkqzWdGLQ5bM5AB5vobgsDVhzk5p',
    label: 'HfAiup...hzk5p',
    category: 'influencer',
    totalPnl: 53484,
    winRate: 0,
    totalTrades: 532,
    favoriteTokens: ["BUU", "MAD", "Celene"],
    verified: false,
    description: 'Robinhood KOL. $53,484 P&L across 50 tokens.',
  },
  {
    id: '147',
    address: 'H7zgEzrkZeXfVa8fRcwAmkjLsoEP5mwfHHrBeh3yUi6y',
    label: 'H7zgEz...yUi6y',
    category: 'influencer',
    totalPnl: 52498,
    winRate: 0,
    totalTrades: 497,
    favoriteTokens: ["Lobstar", "crust", "ok"],
    verified: false,
    description: 'Robinhood KOL. $52,498 P&L across 50 tokens.',
  },
  {
    id: '148',
    address: 'GPH7ZTLvt8JNPHQvWcj8CasrqB9zDUH6wfk177ixSdcT',
    label: 'GPH7ZT...xSdcT',
    category: 'influencer',
    totalPnl: 51414,
    winRate: 0,
    totalTrades: 788,
    favoriteTokens: ["maxxing", "MR", "SCUBA"],
    verified: false,
    description: 'Robinhood KOL. $51,414 P&L across 50 tokens.',
  },
  {
    id: '149',
    address: '8M2CBMSKFk4Xvg6rrfdpVXMTX1F8WMUawUa1T6NE68Vd',
    label: '8M2CBM...E68Vd',
    category: 'influencer',
    totalPnl: 50039,
    winRate: 0,
    totalTrades: 6248,
    favoriteTokens: ["pippin"],
    verified: false,
    description: 'Robinhood KOL. $50,039 P&L across 1 tokens.',
  },
  {
    id: '150',
    address: 'AbG8qwk8UTjKQRafv2syr5Rv1sEW5PkQvhKKAUjzK2fR',
    label: 'AbG8qw...zK2fR',
    category: 'influencer',
    totalPnl: 48306,
    winRate: 0,
    totalTrades: 5678,
    favoriteTokens: ["Lobstar", "BP", "BigTrout"],
    verified: false,
    description: 'Robinhood KOL. $48,306 P&L across 50 tokens.',
  },
  {
    id: '151',
    address: '7jAiyvJMDRqRqx7N3AZiJfdU66aErUXFWqUWBUJLxHug',
    label: '7jAiyv...LxHug',
    category: 'influencer',
    totalPnl: 47302,
    winRate: 0,
    totalTrades: 2173,
    favoriteTokens: ["Punch", "Buttcoin", "CRUST"],
    verified: false,
    description: 'Robinhood KOL. $47,302 P&L across 50 tokens.',
  },
  {
    id: '152',
    address: '8UT27jiUjbukir1jSMfxiYVwfso2mPM92wcuphQAFTnb',
    label: '8UT27j...AFTnb',
    category: 'influencer',
    totalPnl: 45754,
    winRate: 0,
    totalTrades: 1504,
    favoriteTokens: ["Punch", "ORAMAMA", "liquid"],
    verified: false,
    description: 'Robinhood KOL. $45,754 P&L across 50 tokens.',
  },
  {
    id: '153',
    address: '69oHSdMY2RLKFuSCHzr4L5itZPWu65pPCR9hQSoLrPjA',
    label: '69oHSd...LrPjA',
    category: 'influencer',
    totalPnl: 45356,
    winRate: 0,
    totalTrades: 767,
    favoriteTokens: ["EARNFI", "ZAUTH", "VNTR"],
    verified: false,
    description: 'Robinhood KOL. $45,356 P&L across 50 tokens.',
  },
  {
    id: '154',
    address: 'GwqXyg9xVpvRkNNjWE2rYPWa3UpeNEJHBKG2JAtiR7mM',
    label: 'GwqXyg...iR7mM',
    category: 'influencer',
    totalPnl: 41544,
    winRate: 0,
    totalTrades: 315,
    favoriteTokens: ["maxxing", "FILL", "Harry"],
    verified: false,
    description: 'Robinhood KOL. $41,544 P&L across 50 tokens.',
  },
  {
    id: '155',
    address: 'AcGJSCxBsrfmzYyEKdwNScSYzNkZsWt9ftMKywbCRTvr',
    label: 'AcGJSC...CRTvr',
    category: 'influencer',
    totalPnl: 37584,
    winRate: 0,
    totalTrades: 3130,
    favoriteTokens: ["Punch", "LOG", "Jellybean"],
    verified: false,
    description: 'Robinhood KOL. $37,584 P&L across 45 tokens.',
  },
  {
    id: '156',
    address: '7x6qE3DRMW2ZCgT1YQuBLePiheEWw7qjH6rYjj6GDtEd',
    label: '7x6qE3...GDtEd',
    category: 'influencer',
    totalPnl: 33789,
    winRate: 0,
    totalTrades: 388,
    favoriteTokens: ["SID", "COW", "MOLTY"],
    verified: false,
    description: 'Robinhood KOL. $33,789 P&L across 50 tokens.',
  },
  {
    id: '157',
    address: 'GGBn7EszMni4dPy8HuJiis35dwzHxhDkUGpWTXLoxNBw',
    label: 'GGBn7E...oxNBw',
    category: 'influencer',
    totalPnl: 31511,
    winRate: 0,
    totalTrades: 47069,
    favoriteTokens: ["SKR", "pippin", "BOSS"],
    verified: false,
    description: 'Robinhood KOL. $31,511 P&L across 8 tokens.',
  },
  {
    id: '158',
    address: 'GKP9JmjH4G8vkQEP8nhC2wYDBX7KufmCzwr8bnCtNTkv',
    label: 'GKP9Jm...tNTkv',
    category: 'influencer',
    totalPnl: 31376,
    winRate: 0,
    totalTrades: 378,
    favoriteTokens: ["CUM", "MIM", "RKT"],
    verified: false,
    description: 'Robinhood KOL. $31,376 P&L across 50 tokens.',
  },
  {
    id: '159',
    address: 'FbHpocT8oxaufUKYzA2bqXvFq7adRpuAyi6KoggwPPwj',
    label: 'FbHpoc...wPPwj',
    category: 'influencer',
    totalPnl: 30523,
    winRate: 0,
    totalTrades: 491,
    favoriteTokens: ["maxxing", "KNIGHT", "GAM"],
    verified: false,
    description: 'Robinhood KOL. $30,523 P&L across 50 tokens.',
  },
  {
    id: '160',
    address: '7ySPLqH5oH9z2jNvrwjbF6j3xMnXjJosEo2xf6g9VHx2',
    label: '7ySPLq...9VHx2',
    category: 'influencer',
    totalPnl: 28496,
    winRate: 0,
    totalTrades: 1219,
    favoriteTokens: ["maxxing", "PLB", "Buttcoin"],
    verified: false,
    description: 'Robinhood KOL. $28,496 P&L across 50 tokens.',
  },
  {
    id: '161',
    address: 'CjytYP34q9F3vLrgFtdmXPfPambNJFD4du6UBXzfr9ce',
    label: 'Cjyt 40% WR',
    category: 'influencer',
    totalPnl: 27257,
    winRate: 0,
    totalTrades: 372,
    favoriteTokens: ["three", "RKC", "DEGEN"],
    verified: false,
    description: 'Robinhood KOL. $27,257 P&L across 50 tokens.',
  },
  {
    id: '162',
    address: '3w4uBNqP5rHDsTT5yTnjmoeUt9w2YoiMpMD4YtaJ9CWi',
    label: '3w4uBN...J9CWi',
    category: 'influencer',
    totalPnl: 25674,
    winRate: 0,
    totalTrades: 1865,
    favoriteTokens: ["BOBO", "OPAN", "JUP"],
    verified: false,
    description: 'Robinhood KOL. $25,674 P&L across 50 tokens.',
  },
  {
    id: '163',
    address: 'HhU72Yen8cwikE8sLQR6Yuy8btujSLW1S3Tm6nrgMuQc',
    label: 'HhU72Y...gMuQc',
    category: 'influencer',
    totalPnl: 23534,
    winRate: 0,
    totalTrades: 237,
    favoriteTokens: ["Punch", "BABYGOAT", "PRM"],
    verified: false,
    description: 'Robinhood KOL. $23,534 P&L across 50 tokens.',
  },
  {
    id: '164',
    address: '5uEkJanck3tS9ySthtQta8ExT7y5YhjQx1VxuiqKBefF',
    label: '5uEkJa...KBefF',
    category: 'influencer',
    totalPnl: 21791,
    winRate: 0,
    totalTrades: 778,
    favoriteTokens: ["maxxing", "Chameleon", "GTAVI"],
    verified: false,
    description: 'Robinhood KOL. $21,791 P&L across 50 tokens.',
  },
  {
    id: '165',
    address: 'FUtscwCoLtRbZ2FZ9HUQbtwDSQ7gtC97bwDx6Pd9yut3',
    label: 'FUtscw...9yut3',
    category: 'influencer',
    totalPnl: 19328,
    winRate: 0,
    totalTrades: 95,
    favoriteTokens: ["maxxing", "LORIA", "TROLLBOY"],
    verified: false,
    description: 'Robinhood KOL. $19,328 P&L across 6 tokens.',
  },
  {
    id: '166',
    address: '4FFEWcKSaJ3PYUGQEnHjsynDnb3KSdqK7ZNPyiiBj5YP',
    label: 'criptow_',
    category: 'influencer',
    totalPnl: 19321,
    winRate: 0,
    totalTrades: 1843,
    favoriteTokens: ["BioLLM", "CLASH", "FOLD"],
    verified: false,
    description: 'Robinhood KOL. $19,321 P&L across 50 tokens.',
  },
  {
    id: '167',
    address: 'Gi42D22oTkkZEm8GpZkU6sSiPZNhhnUKyeJFNPuocQS8',
    label: 'Gi42D2...ocQS8',
    category: 'influencer',
    totalPnl: 18016,
    winRate: 0,
    totalTrades: 610,
    favoriteTokens: ["EYED", "BILLY", "FLOKI"],
    verified: false,
    description: 'Robinhood KOL. $18,016 P&L across 50 tokens.',
  },
  {
    id: '168',
    address: 'GtHSNvamWC3zR2KHPwzZJpkq9jT3bDgixdz76tjH74Fs',
    label: 'GtHSNv...H74Fs',
    category: 'influencer',
    totalPnl: 17063,
    winRate: 0,
    totalTrades: 273,
    favoriteTokens: ["maxxing", "AVO", "KAI"],
    verified: false,
    description: 'Robinhood KOL. $17,063 P&L across 50 tokens.',
  },
  {
    id: '169',
    address: '8xJ7SPVX2m4RXVnWMkC11XJNwd5WcJMi4BTupdYmP9T7',
    label: '8xJ7SP...mP9T7',
    category: 'influencer',
    totalPnl: 16971,
    winRate: 0,
    totalTrades: 161,
    favoriteTokens: ["ALPHA", "SPX", "Sorkincoin"],
    verified: false,
    description: 'Robinhood KOL. $16,971 P&L across 50 tokens.',
  },
  {
    id: '170',
    address: 'FzEg6qzYtqM1XqQuCX8NuqowXQ2tzfV8NHzyXXCzKw5A',
    label: 'FzEg6q...zKw5A',
    category: 'influencer',
    totalPnl: 16499,
    winRate: 0,
    totalTrades: 239,
    favoriteTokens: ["Punch", "SOL\u4eba\u751f", "Jellybean"],
    verified: false,
    description: 'Robinhood KOL. $16,499 P&L across 50 tokens.',
  },
  {
    id: '171',
    address: '35KH3egx9yfbhQr8njKS1V2RG9pCYxF2Hii5GLjaRhqF',
    label: '35KH3e...aRhqF',
    category: 'influencer',
    totalPnl: 15308,
    winRate: 0,
    totalTrades: 1014,
    favoriteTokens: ["SOLCEX", "SEEKAI", "PegeCoin"],
    verified: false,
    description: 'Robinhood KOL. $15,308 P&L across 50 tokens.',
  },
  {
    id: '172',
    address: 'HPHoEV9LPL2ziKCztSmJmFnJTmVgJXUHQqZypuAaNuE9',
    label: 'HPHoEV...aNuE9',
    category: 'influencer',
    totalPnl: 14719,
    winRate: 0,
    totalTrades: 586,
    favoriteTokens: ["EYED", "CATCOIN", "RIV"],
    verified: false,
    description: 'Robinhood KOL. $14,719 P&L across 50 tokens.',
  },
  {
    id: '173',
    address: 'Gvp1PXk4qgoUzoaTRbZmx3WdY7taPrqV6j2fbBVxdd4R',
    label: 'Gvp1PX...xdd4R',
    category: 'influencer',
    totalPnl: 11645,
    winRate: 0,
    totalTrades: 491,
    favoriteTokens: ["OPAN", "MESA", "HAPPY"],
    verified: false,
    description: 'Robinhood KOL. $11,645 P&L across 50 tokens.',
  },
  {
    id: '174',
    address: '3ryCcpVYUQhQbCsw6rjCeZ9iR2dQUFXYvA4dSHcGqty1',
    label: '3ryCcp...Gqty1',
    category: 'influencer',
    totalPnl: 11225,
    winRate: 0,
    totalTrades: 443,
    favoriteTokens: ["Lobstar", "Clude", "21"],
    verified: false,
    description: 'Robinhood KOL. $11,225 P&L across 50 tokens.',
  },
  {
    id: '175',
    address: '5STUuhrL8kJ4up9spEY39VJ6ibQCFrg8x8cRV5UeEcfv',
    label: '5STUuh...eEcfv',
    category: 'influencer',
    totalPnl: 10865,
    winRate: 0,
    totalTrades: 476,
    favoriteTokens: ["maxxing", "GOY", "WOAH"],
    verified: false,
    description: 'Robinhood KOL. $10,865 P&L across 50 tokens.',
  },
  {
    id: '176',
    address: 'A6fcScrJQoSs6JKXQX5snSca1JtGG8tNRtjAhzUKCU7d',
    label: 'A6fcSc...KCU7d',
    category: 'influencer',
    totalPnl: 10116,
    winRate: 0,
    totalTrades: 878,
    favoriteTokens: ["gork", "pippin", "Distorted"],
    verified: false,
    description: 'Robinhood KOL. $10,116 P&L across 50 tokens.',
  },
  {
    id: '177',
    address: 'Df7u7ZhusUgR2WbuVoiWRveLWPrbjvEmPwHoiHqHhS4',
    label: 'Df7u7Z...qHhS4',
    category: 'influencer',
    totalPnl: 10064,
    winRate: 0,
    totalTrades: 363,
    favoriteTokens: ["MOB", "BABYPNUT", "$LANDLORD"],
    verified: false,
    description: 'Robinhood KOL. $10,064 P&L across 50 tokens.',
  },
  {
    id: '178',
    address: '99QtQsYhpwCuhBXEZmouTaVLvbwaBhPWUtrn3M751ZBy',
    label: '99QtQs...51ZBy',
    category: 'influencer',
    totalPnl: 8432,
    winRate: 0,
    totalTrades: 220,
    favoriteTokens: ["ACM", "TRUMP", "Butthole"],
    verified: false,
    description: 'Robinhood KOL. $8,432 P&L across 50 tokens.',
  },
  {
    id: '179',
    address: 'CQAAuYc5Vwng21vAjjiqBD1kM8sjU5gT9vhkUs889BZh',
    label: 'CQAAuY...89BZh',
    category: 'influencer',
    totalPnl: 7351,
    winRate: 0,
    totalTrades: 530,
    favoriteTokens: ["FKH", "WAR", "maxxing"],
    verified: false,
    description: 'Robinhood KOL. $7,351 P&L across 31 tokens.',
  },
  {
    id: '180',
    address: '9DGRZg9ehm3QJRzXszS1qmp6XGwQEmiQVvKWgBubqYsu',
    label: '9DGRZg...bqYsu',
    category: 'influencer',
    totalPnl: 6130,
    winRate: 0,
    totalTrades: 514,
    favoriteTokens: ["monk", "maxxing", "GIGAFLY"],
    verified: false,
    description: 'Robinhood KOL. $6,130 P&L across 50 tokens.',
  },
  {
    id: '181',
    address: 'CXuXPRdSmRXXjYSoJZ4UcVcScHnW8t44hSXqH9Wrig75',
    label: 'CXuXPR...rig75',
    category: 'influencer',
    totalPnl: 5612,
    winRate: 0,
    totalTrades: 36,
    favoriteTokens: ["maxxing", "Punch", "AISLOP"],
    verified: false,
    description: 'Robinhood KOL. $5,612 P&L across 6 tokens.',
  },
  {
    id: '182',
    address: 'EpTPPrqzQUgtJaZ7XUUiK3nuHe1MusbjLiQuJx3kNnL6',
    label: 'EpTP...NnL6',
    category: 'influencer',
    totalPnl: 5286,
    winRate: 0,
    totalTrades: 207,
    favoriteTokens: ["AgenC", "DATACLAW", "Pinch"],
    verified: false,
    description: 'Robinhood KOL. $5,286 P&L across 50 tokens.',
  },
  {
    id: '183',
    address: '9uyuUv8zVgq72DuYTvfD5zgZgEzyUXygye4U1jatrRLd',
    label: '9uyuUv...trRLd',
    category: 'influencer',
    totalPnl: 5282,
    winRate: 0,
    totalTrades: 298,
    favoriteTokens: ["maxxing", "HELIO", "MemesAI"],
    verified: false,
    description: 'Robinhood KOL. $5,282 P&L across 31 tokens.',
  },
  {
    id: '184',
    address: 'AcNJaBMwLbA9YXWhZSawtFBk7N4piYAdTTjWjiqobeqm',
    label: 'AcNJaB...obeqm',
    category: 'influencer',
    totalPnl: 4691,
    winRate: 0,
    totalTrades: 227,
    favoriteTokens: ["Lobstar", "CHIBI", "Ghibli"],
    verified: false,
    description: 'Robinhood KOL. $4,691 P&L across 50 tokens.',
  },
  {
    id: '185',
    address: 'ADZmCZVVQxzyUkXaTtL9JYQATRL4RVqzcmsJ1jtgYFL9',
    label: 'ADZmCZ...gYFL9',
    category: 'influencer',
    totalPnl: 4311,
    winRate: 0,
    totalTrades: 52,
    favoriteTokens: ["Lobstar", "LASZLO", "rig"],
    verified: false,
    description: 'Robinhood KOL. $4,311 P&L across 14 tokens.',
  },
  {
    id: '186',
    address: 'EFiU8yVYiBXcmCa1Bjajsx9xbFh6SKWPPPpAxHvTdTS1',
    label: 'EFiU8y...TdTS1',
    category: 'influencer',
    totalPnl: 3944,
    winRate: 0,
    totalTrades: 217,
    favoriteTokens: ["Dunald", "Turtle", "NUBBY"],
    verified: false,
    description: 'Robinhood KOL. $3,944 P&L across 50 tokens.',
  },
  {
    id: '187',
    address: 'HFVbhPuXKkvRDmeR2H4sNe9BLKyurgXCXbt61NbzX9Wb',
    label: 'HFVbhP...zX9Wb',
    category: 'influencer',
    totalPnl: 3518,
    winRate: 0,
    totalTrades: 29,
    favoriteTokens: ["SOLCEX", "TROLL", "CHILLGUY"],
    verified: false,
    description: 'Robinhood KOL. $3,518 P&L across 6 tokens.',
  },
  {
    id: '188',
    address: '8J7EZ3WFAgXc9AXSnKaZfTc2dzUAC2PR8esUNpoxSNBz',
    label: '8J7EZ3...xSNBz',
    category: 'influencer',
    totalPnl: 2937,
    winRate: 0,
    totalTrades: 644,
    favoriteTokens: ["RYS", "QPAY", "BARSIK"],
    verified: false,
    description: 'Robinhood KOL. $2,937 P&L across 50 tokens.',
  },
  {
    id: '189',
    address: '73WhrhGfk9GFZkq5uuHMQpyukJBKmZP69RE6kdVj3ksC',
    label: '73Whrh...j3ksC',
    category: 'influencer',
    totalPnl: 2834,
    winRate: 0,
    totalTrades: 169,
    favoriteTokens: ["maxxing", "abcdefg", "HIMS"],
    verified: false,
    description: 'Robinhood KOL. $2,834 P&L across 29 tokens.',
  },
  {
    id: '190',
    address: '7jN6hUdNBdkK12wVM2iydxx9hzsxUhUppmr99Aeu6cKb',
    label: '7jN6hU...u6cKb',
    category: 'influencer',
    totalPnl: 2397,
    winRate: 0,
    totalTrades: 16,
    favoriteTokens: ["ZEC", "kV-AlUSDC", "k-MEVC-SOL"],
    verified: false,
    description: 'Robinhood KOL. $2,397 P&L across 3 tokens.',
  },
  {
    id: '191',
    address: 'H58NhTNB4mLL3g6c72j8jy4tTxK3ZhuPGtMkJSj4JFBm',
    label: 'H58NhT...4JFBm',
    category: 'influencer',
    totalPnl: 2154,
    winRate: 0,
    totalTrades: 52,
    favoriteTokens: ["GHOST", "XERIS", "SOLCEX"],
    verified: false,
    description: 'Robinhood KOL. $2,154 P&L across 6 tokens.',
  },
  {
    id: '192',
    address: 'J4t67WU8BfjQp1YG9TVbPhNXS84sfZaarmi9jFx9Bpuk',
    label: 'J4t67W...9Bpuk',
    category: 'influencer',
    totalPnl: 2046,
    winRate: 0,
    totalTrades: 580,
    favoriteTokens: ["SOLCEX", "CP", "CIF"],
    verified: false,
    description: 'Robinhood KOL. $2,046 P&L across 12 tokens.',
  },
  {
    id: '193',
    address: 'FZU5bqYanpBuBzGDHshQL9rZb8PYS45tyP9q44eQpGsK',
    label: 'FZU5bq...QpGsK',
    category: 'influencer',
    totalPnl: 1836,
    winRate: 0,
    totalTrades: 5540,
    favoriteTokens: ["jailstool", "GOOGLx", "GOR"],
    verified: false,
    description: 'Robinhood KOL. $1,836 P&L across 50 tokens.',
  },
  {
    id: '194',
    address: 'GXSx5in2dhCwcQtcaNfNb8GFBzynS3MhvAwNo7MZ4dcE',
    label: 'GXSx5i...Z4dcE',
    category: 'influencer',
    totalPnl: 1787,
    winRate: 0,
    totalTrades: 261,
    favoriteTokens: ["Duchi", "BILLY", "JUP"],
    verified: false,
    description: 'Robinhood KOL. $1,787 P&L across 50 tokens.',
  },
  {
    id: '195',
    address: 'Hgyp6Z6pUW1EHCCmnW8GaacWQPiVH8WtFugsppsTK4ep',
    label: 'Hgyp6Z...TK4ep',
    category: 'influencer',
    totalPnl: 1484,
    winRate: 0,
    totalTrades: 331,
    favoriteTokens: ["lou", "USD", "OWLFEED"],
    verified: false,
    description: 'Robinhood KOL. $1,484 P&L across 50 tokens.',
  },
  {
    id: '196',
    address: 'gk8775aRMnVKhdWbFUtzKxg2t1oUP23CQEP3LtppgMB',
    label: 'gk8775...ppgMB',
    category: 'influencer',
    totalPnl: 1434,
    winRate: 0,
    totalTrades: 217,
    favoriteTokens: ["MOODUANG", "PEDRO", "MOOYOR"],
    verified: false,
    description: 'Robinhood KOL. $1,434 P&L across 50 tokens.',
  },
  {
    id: '197',
    address: '9dDBXrwbtX2debz8tVxFMQA4pdwUpPNVd9xG6NYjq5h',
    label: '9dDBXr...Yjq5h',
    category: 'influencer',
    totalPnl: 1109,
    winRate: 0,
    totalTrades: 285,
    favoriteTokens: ["assface", "Hobbes", "APU"],
    verified: false,
    description: 'Robinhood KOL. $1,109 P&L across 50 tokens.',
  },
  {
    id: '198',
    address: 'AKXFduz9tWxcvkYRs9Zu92vMVen2cFe9S9xX1QytW3Kk',
    label: 'AKXFdu...tW3Kk',
    category: 'influencer',
    totalPnl: 795,
    winRate: 0,
    totalTrades: 14,
    favoriteTokens: ["CATANA", "Rome", "EDWIN"],
    verified: false,
    description: 'Robinhood KOL. $795 P&L across 5 tokens.',
  },
  {
    id: '199',
    address: 'JD9L13WnsSxNdhcrWGfojS4triMmPCrSPPSFR85rvTnU',
    label: 'JD9L13...rvTnU',
    category: 'influencer',
    totalPnl: 627,
    winRate: 0,
    totalTrades: 552,
    favoriteTokens: ["\u6211\u7684\u5200\u76fe", "URANUS", "SCUBA"],
    verified: false,
    description: 'Robinhood KOL. $627 P&L across 30 tokens.',
  },
  {
    id: '200',
    address: 'ZU3ULgYytLXu3VniAxkBpdrqHpks3Qw8xHZnV1d4HNe',
    label: 'ZU3ULg...d4HNe',
    category: 'influencer',
    totalPnl: 507,
    winRate: 0,
    totalTrades: 134,
    favoriteTokens: ["FINU", "CAT", "2NDCOMING"],
    verified: false,
    description: 'Robinhood KOL. $507 P&L across 5 tokens.',
  },
  {
    id: '201',
    address: '4jD7btqGE3i9ip5Ex4qfMdN7ubsSZ3VTHbjULTREVLnp',
    label: '4jD7bt...EVLnp',
    category: 'influencer',
    totalPnl: 259,
    winRate: 0,
    totalTrades: 106,
    favoriteTokens: ["SOLCEX", "USOR", "QPAY"],
    verified: false,
    description: 'Robinhood KOL. $259 P&L across 4 tokens.',
  },
  {
    id: '202',
    address: 'BCpKLazCDkHdyekU3nTWgQfgWqp9KCGxPPrt5wHAXpvr',
    label: 'BCpKLa...AXpvr',
    category: 'influencer',
    totalPnl: 10,
    winRate: 0,
    totalTrades: 19,
    favoriteTokens: ["HUSTLE", "SOLCEX"],
    verified: false,
    description: 'Robinhood KOL. $10 P&L across 2 tokens.',
  },
  {
    id: '203',
    address: '6uQ6JsMp1J5yBxYVJA9PHshaumifgP8Ajs4pRcpoYDB9',
    label: '6uQ6Js...oYDB9',
    category: 'influencer',
    totalPnl: 10,
    winRate: 0,
    totalTrades: 4,
    favoriteTokens: ["SOLCEX"],
    verified: false,
    description: 'Robinhood KOL. $10 P&L across 1 tokens.',
  },
];

export const recentTrades: Trade[] = [
  { id: '1', walletId: '1', tokenSymbol: 'BONK', tokenName: 'Bonk', tradeType: 'buy', amount: 2500000, price: 0.000012, pnl: 45000, timestamp: '2026-02-17T09:30:00Z' },
  { id: '2', walletId: '2', tokenSymbol: 'JUP', tokenName: 'Jupiter', tradeType: 'sell', amount: 5000, price: 1.85, pnl: 3200, timestamp: '2026-02-17T09:15:00Z' },
  { id: '3', walletId: '3', tokenSymbol: 'WIF', tokenName: 'Dog Wif Hat', tradeType: 'buy', amount: 15000, price: 0.85, pnl: -1200, timestamp: '2026-02-17T08:45:00Z' },
  { id: '4', walletId: '5', tokenSymbol: 'GIGA', tokenName: 'Giga Chad', tradeType: 'buy', amount: 50000, price: 0.045, pnl: 8500, timestamp: '2026-02-17T08:30:00Z' },
  { id: '5', walletId: '6', tokenSymbol: 'SOL', tokenName: 'Solana', tradeType: 'buy', amount: 500, price: 185.5, pnl: 12500, timestamp: '2026-02-17T07:45:00Z' },
];

export function formatAddress(address: string): string {
  // Show truncated version for display: 5 chars...5 chars
  if (address.length > 15) {
    return `${address.slice(0, 5)}...${address.slice(-5)}`;
  }
  return address;
}

export function formatCurrency(amount: number): string {
  if (amount >= 1000000) {
    return `$${(amount / 1000000).toFixed(2)}M`;
  } else if (amount >= 1000) {
    return `$${(amount / 1000).toFixed(1)}K`;
  }
  return `$${amount.toFixed(2)}`;
}

export function formatPercentage(value: number): string {
  return `${value.toFixed(1)}%`;
}

export function getTopWallets(limit: number = 10): Wallet[] {
  return [...wallets]
    .sort((a, b) => b.totalPnl - a.totalPnl)
    .slice(0, limit);
}

export function getWalletsByCategory(category: string): Wallet[] {
  return wallets.filter(w => w.category === category);
}

export function getWalletByAddress(address: string): Wallet | undefined {
  return wallets.find(w => w.address.toLowerCase() === address.toLowerCase());
}

export function getWalletById(id: string): Wallet | undefined {
  return wallets.find(w => w.id === id);
}
